### ISSUE TITLE
Wrong relation name suggested?

### ISSUE THREAD

**Issue by jose-bittacora** [beyondcode/laravel-query-detector#100]
Hi! First of all for your hard work.

When I try to use this package, I get suggestions to fix N+1 problems as expected, but I get results like this:

Model: MyPackage\Products\Models\Product => Relation: OtherPackage\Models\VatRate - You should add `with(OtherPackage\Models\VatRate)` to eager-load this relation.

This is the relation in Product:

```php
public function vatRate(): BelongsTo
{
    return $this->belongsTo(VatRate::class);
}
```

When I do that, I get an error (relation does not exist). Why is the package reporting class names instead of relation names? I have been hours trying to figure this out but I have failed. I'm completely sure that I am doing something wrong, but I don't know what it is.

The code is working so I guess that the relation is correct.

Thank you

**Comment by vishal4669** [comment]
I am facing the same problem. It is giving the name of Class and as far as I know there is no way to use class in relationship directly.

**Comment by jose-bittacora** [comment]
I have tried to use it in a 2 years old project and the same happens.

**Comment by Jagdish-J-P** [comment]
Does anyone have solution for this issue? Why author is not replying on any issue?

**Comment by Jagdish-J-P** [comment]
Current work around I've found is increasing `QUERY_DETECTOR_THRESHOLD` value to at least 3. And that warning will be hidden.

**Comment by mechelon** [comment]
Not sure what the `QUERY_DETECTOR_THRESHOLD` has to do with this issue.

I'm afraid I cannot reproduce this issue.
For this relation:
```php
    public function post()
    {
        return $this->belongsTo(Post::class);
    }
```


I get this alert text in the browser:
```
Found the following N+1 queries in this request:

Model: App\Models\Comment => Relation: post - You should add "with('post')" to eager-load this relation.
```


If you still have this problem, feel free to reopen with your Laravel version as well as the used output provider and any packages that might affect the relations of your app.
