### ISSUE TITLE
Ability to disable?

### ISSUE THREAD

**Issue by SturmB** [beyondcode/laravel-query-detector#102]
Is there any way to disable this, perhaps in a config file or as an environment variable?

I'm getting a false positive and it's super-annoying. I'd rather not have to uninstall it if I can avoid that.

**Comment by philharmonie** [comment]
https://beyondco.de/docs/laravel-query-detector/usage

**Comment by SturmB** [comment]
Thank you so much, @philharmonie, that's exactly what I was looking for. I now feel rather silly that I never saw that documentation. I'll do better next time.

Thanks again, and take care!
