### ISSUE TITLE
Add support for Laravel 11

### ISSUE THREAD

**Issue by G4Zz0L1** [beyondcode/laravel-query-detector#106]
Laravel 11 is out, can you add support for it?
Thanks in advance!

**Comment by liamjoc** [comment]
In the meantime follow the comments in this PR to get this working with your Laravel 11 App.

https://github.com/beyondcode/laravel-query-detector/pull/105

**Comment by G4Zz0L1** [comment]
Yes, I tried it and it seems to have no problems on my side.
I suppose it can be merged, after your due tests.

**Comment by G4Zz0L1** [comment]
Is there any news for when it will be merged?
Thanks in advance!

**Comment by it-can** [comment]
@mpociot can you merge this and release a new tag/version please?

**Comment by deyan-ardi** [comment]
When Laravel 11.x support will be release?

**Comment by blissjaspis** [comment]
You can use the repo that I have forked and supports Laravel version 11 https://github.com/blissjaspis/laravel-query-detector

**Comment by iqbalhasandev** [comment]
Any update on this?

**Comment by deyan-ardi** [comment]
> Any update on this?

Maybe use the forked repo https://github.com/blissjaspis/laravel-query-detector

**Comment by leo108** [comment]
> You can use the repo that I have forked and supports Laravel version 11 https://github.com/blissjaspis/laravel-query-detector

This is a copy, not a fork.

**Comment by anchan42** [comment]
> You can use the repo that I have forked and supports Laravel version 11 https://github.com/blissjaspis/laravel-query-detector

Thanks a lot :)
Clearly this is meant as a temporary solution until the main repo is updated. No need to jump about 😚
