### ISSUE TITLE
Is it advisable to use this in production?

### ISSUE THREAD

**Issue by CurvesTech** [beyondcode/laravel-query-detector#109]
Hi,
 
I am planning to use this package in prod environment. Is there any concern in doing that, like could it potentially slow down the application?  or it should be used for dev only? 

My plan is to listen for this event 
`\BeyondCode\QueryDetector\Events\QueryDetected`

and send report the detected queries to our chat app.

**Comment by mechelon** [comment]
This tool is made with development purposes in mind and therefore I would not advise you to use it in production.
