### ISSUE TITLE
Error on redirect

### ISSUE THREAD

**Issue by jpmurray** [beyondcode/laravel-query-detector#2]
Hello there!

I'm submitting data of a form via `POST` and getting this error:

```
Argument 1 passed to BeyondCode\QueryDetector\QueryDetector::applyOutput() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\RedirectResponse given, called in /vendor/beyondcode/laravel-query-detector/src/QueryDetector.php on line 182
```

I think it's because I return something like `return redirect()->route('users.edit', ['user' => $user->uuid]);` in my controller... ?

**Comment by mpociot** [comment]
Thanks for reporting this issue. Yeah, redirect responses were not handled correctly. 
I fixed this issue and tagged a new version.
