### ISSUE TITLE
config file publishing doesn't work

### ISSUE THREAD

**Issue by aand18** [beyondcode/laravel-query-detector#28]
Running `php artisan vendor:publish --provider=BeyondCode\\QueryDetector\\QueryDetectorServiceProvider` doesn't create the config file. Yet, the console says 'Publishing complete.'

**Comment by bvipul** [comment]
I have tried it with fresh installation of this package. And the command is working. But your problem seems to be a permission issue.

**Comment by crashmxx** [comment]
The documentation "suppose" you use the auto discovery package of laravel, but if you are in a version of laravel < 5.5 or you have disabled the auto discovery package (see https://mcampbell508.github.io/2018/01/20/disable-laravel-autodiscovery/), you need to add to your config/app.php file the serviceProvider mentioned, before launch the publish command

**Comment by kurumbus** [comment]
I had the same problem, but when I ran it with single slashes instead of double it worked
BeyondCode\\QueryDetector\\QueryDetectorServiceProvider -> BeyondCode\QueryDetector\QueryDetectorServiceProvider

Why double slashes anyways?

**Comment by krns** [comment]
Just had the same problem. For me the `php artisan vendor:publish --provider=BeyondCode\\QueryDetector\\QueryDetectorServiceProvider` worked and `php artisan vendor:publish --provider=BeyondCode\QueryDetector\QueryDetectorServiceProvider` not.
