### ISSUE TITLE
[Question] Config Except

### ISSUE THREAD

**Issue by johannesschobel** [beyondcode/laravel-query-detector#3]
Dear @mpociot ,

when i read the docs for the config file, i stumbled upon the `querydetector.except` param and the corresponding comment:
```
/*
 * Here you can whitelist model relations.
 *
 * Right now, you need to define the model relation both as the class name and the attribute name on the model.
 * So if an "Author" model would have a "posts" relation that points to a "Post" class, you need to add both
 * the "posts" attribute and the "Post::class", since the relation can get resolved in multiple ways.
 */
```

Why is it that you need to define the relationship name and the corresponding class? Wouldn't the relationship be actually enough? And - if not - wouldn't it be better to define it like this:

```
'except' => [
   Author::class => [
      'posts' => Post::class,
      'comments' => Comment::class,
   ]
]
```

in order to properly map the Model to its corresponding relationship?

All the best,
cheers

**Comment by mpociot** [comment]
Hi,

okay - so the relation detection only works by listening for SQL queries and then use `debug_backtrace` to find out if the query came from a relation.

This can happen in two ways:

1. You call a relation by using the model property:

```php
foreach($posts as $post) {
    echo $post->author->name;
}
```

In this case, the package would detect that the `author` relation is being called.

2. You cann a relation by using the relation query builder:

```php
foreach($posts as $post) {
    echo $post->authors()->first()->name;
}
```

In this case, the package can only detect that a relation for the `Author::class` model was accessed. Unfortunately I can not detect the attribute name in the backtrace, so I have no idea if it was the `authors` relation or maybe a different one.

So if one model would have two relations, that both point to the same model, I do not know which one was accessed.
