### ISSUE TITLE
Error when upgrading when Laravel 5.6 to Laravel 5.7

### ISSUE THREAD

**Issue by reymark-torres** [beyondcode/laravel-query-detector#39]
beyondcode/laravel-query-detector 0.4.1 requires illuminate/support 5.5.*|5.6.* -> satisfiable by laravel/framework[v5.6.38, 5.5.x-dev, 5.6.x-dev], illuminate/support[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].

Any updates? Thanks.

**Comment by marcmascort** [comment]
In the [0.6.0](https://github.com/beyondcode/laravel-query-detector/releases/tag/0.6.0) release was added compatibility for Laravel 5.7. Update your version.

```
composer update beyondcode/laravel-query-detector
```

**Comment by reymark-torres** [comment]
Thank you very much for the information! :)
