### ISSUE TITLE
Please release version 1.0.2

### ISSUE THREAD

**Issue by jmsfwk** [beyondcode/laravel-query-detector#51]
Could you please create a release that includes the fix from #34?

**Comment by vaughany** [comment]
^^ This, please. I'm running into the error `DebugBar\DebugBarException thrown with message "N+1 Queries is already a registered collector"` when running PHPUnit tests, and cannot find any way around the issue other than to disable the test that causes the above error to be thrown.

**Comment by egorsmkv** [comment]
You can use git in order to get code from the repository.
