### ISSUE TITLE
Question: Is that possible to test route for a N+1 problem

### ISSUE THREAD

**Issue by approached** [beyondcode/laravel-query-detector#52]
Hi@all

Is that possible to test route for a N+1 problem?

**Comment by victor-priceputu** [comment]
I am doing this, but you need to make a feature test. I am extending the `TestCase` and calling the route using `$this->postJson(route($this->endpointName), $requestData);`.

But make sure in your testing configuration your have the module enabled.
The query detector is injecting middleware, which is what does the job, so unit testing will not give you any information.
Also, make sure you are logging the N+1 problems in the logs, so you can see them.
