### ISSUE TITLE
Can't install with php 7

### ISSUE THREAD

**Issue by Silvio12** [beyondcode/laravel-query-detector#6]
when i try ti install this package i get the following error message:

[InvalidArgumentException]                                                    
  Package beyondcode/laravel-query-detector at version  has a PHP requirement 
incompatible with your PHP version (7.0.2)

**Comment by tvbeek** [comment]
The required version is 7.1 (or higher)
See the composer.json file https://github.com/beyondcode/laravel-query-detector/blob/master/composer.json#L19

**Comment by mpociot** [comment]
This package require PHP 7.1 or higher, sorry.
