### ISSUE TITLE
Unable to public the package in Laravel 7

### ISSUE THREAD

**Issue by Nilanth** [beyondcode/laravel-query-detector#61]
When we run this command

`php artisan vendor:publish --provider=BeyondCode\QueryDetector\QueryDetectorServiceProvider
`
Getting this error
**Unable to locate publishable resources.**
Could you please help  to resolve this issue?

**Comment by ryu022304** [comment]
I run below command and it works

`php artisan vendor:publish --provider=BeyondCode\\QueryDetector\\QueryDetectorServiceProvider`

**Comment by lypsisrudiansyah** [comment]
> I run below command and it works
> 
> `php artisan vendor:publish --provider=BeyondCode\\QueryDetector\\QueryDetectorServiceProvider`
> or
> `php artisan vendor:publish --provider="BeyondCode\QueryDetector\QueryDetectorServiceProvider"`

Thanks for this solution, it works

**Comment by hasnatbabur** [comment]
Please update the readme file. People feel confusing!

**Comment by mpociot** [comment]
Thanks, this is now fixed in the readme
