### ISSUE TITLE
Question: Is it possible for warning to be suppressed for package code?

### ISSUE THREAD

**Issue by ziming** [beyondcode/laravel-query-detector#66]
Say some package controller code has an N+1 query. I'm aware of that but since it's not my code. I rather not get the warnings and dialog popups.

Is it possible to set that?

**Comment by mpociot** [comment]
You could add the model/relation to the array of exceptions

**Comment by ziming** [comment]
I want to be notified if I use those models myself but I don't want to be notified if it is the package controller code making the mistakes
