### ISSUE TITLE
Incompatibility with Laravel 8

### ISSUE THREAD

**Issue by michele-grifa** [beyondcode/laravel-query-detector#72]
I tried to install the package on Laravel 8 and when i try to load a page the error is the following:

```php
Illuminate\Container\Container::bind(): Argument #2 ($concrete) must be of type Closure|string|null
```

How i can resolve?

**Comment by dansku** [comment]
Yup, just got here as well

**Comment by ndberg** [comment]
It's working on the current release v8.37
