### ISSUE TITLE
Error "Argument #2 ($concrete) must be of type Closure|string|null" after install

### ISSUE THREAD

**Issue by ivex001** [beyondcode/laravel-query-detector#81]
Hi there im receiving this error after installation. If i remove the package the error goes away.
![Captura de ecrã 2021-03-11 211739](https://user-images.githubusercontent.com/4996638/110862734-3da45680-82af-11eb-92de-106f08809d0a.png)

Im using laravel 8 and php 8.0.2
 Thanks in advance

**Comment by SenTisso** [comment]
Same for me.
Laravel 8.31, PHP 7.4.3

**Comment by Mokei-it** [comment]
The same for me: Laravel 8.32.1, PHP 7.4.1
Thank you in advance!

**Comment by buzzclue** [comment]
Same for me.
Laravel 8.33, PHP 8.0

**Comment by soufiansaidi** [comment]
Same for me.
Laravel 8, PHP 7.4

**Comment by onuruslu** [comment]
Same for me.
Laravel 8.29 PHP 7.3.23

**Comment by rvanbaalen** [comment]
Jup.. the current release seems broken.

**Comment by lilouch** [comment]
Same here

**Comment by ndberg** [comment]
I'm on PHP 7.4 and Laravel 8.37 and it's working

**Comment by zlokomatic** [comment]
Problem is your configuration is cached.

```sail artisan optimize:clear``` should fix it

**Comment by reasecret** [comment]
I got same error and php artisan config:cache solved my issue.
Laravel 8 and PHP 7.4

**Comment by asandri-mmo** [comment]
:+1:
