### ISSUE TITLE
Detecting N1's that already have with() + Namespace issue

### ISSUE THREAD

**Issue by Braunson** [beyondcode/laravel-query-detector#9]
For example the code it's alerting on:

```
return Spark::team()->with('users', 'owner')
                    ->where('id', $id)
                    ->first();
```

Alert is:

```
Model: App\Models\Team => Relation: App\Models\User - You should add "with('AppModelsUser')" to eager-load this relation.
```

Also there seems to be a namespace issue as you can see inside the `with` above removes the `\`

**Comment by mpociot** [comment]
Hi,

can you come up with a reproducible code that we can use in our test cases?
Maybe the issue comes from nested relations + eager loading

**Comment by scottzirkel** [comment]
I'm seeing the same popup when I have set the eager loading on the models with property. Moving it into each query alleviated it.

Also moving it there saved me a few more queries. I had always thought it was the same either way. Good to know!
