### ISSUE TITLE
ErrorException QueryDetector.php:78

### ISSUE THREAD

**Issue by tomohirohiratsuka** [beyondcode/laravel-query-detector#91]
Hi, thank you for creating awesome package.

I've been facing error while debugging api.

```
error  Undefined array key 0 Array(1) { userId: 5 } 
ErrorException QueryDetector.php:78
```

Looking at the source code, I think the cause is that an associative array is returned where an array is expected to be returned, but I'm not sure if I'm using it wrong or not.
https://github.com/beyondcode/laravel-query-detector/blob/8261d80c71c97e994c1021fe5c3bd2a1c27106fc/src/QueryDetector.php#L76

**Comment by scottzirkel** [comment]
It looks like `$sources` can return an empty array, but there is no check for that, so the error is thrown from the next line, which attempts to access the first value in the array. Hopefully the PR can be looked at soon and fixed, this has been plaguing me for a few months now. I still don't know how to cause it, I only know some of the queries are logged properly, and some aren't.
